name        : irssi
version     : 0.8.19
release     : 7
source     :
    - https://github.com/irssi-import/irssi/releases/download/0.8.19/irssi-0.8.19.tar.xz : 4ca0040548e814ea93eb7d602ab7d6d379afcbbdf10e84160523ce69c73ee5d3
license     : GPL-2.0+
summary     : Terminal based IRC client
component   : network.irc
description : |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more. The SolusOS build includes proxy and bot.
setup      : |
    %configure --sysconfdir=/etc/irssi \
               --with-socks \
               --with-bot \
               --with-proxy \
               --with-ncurses
build      : |
    %make
install    : |
    %make_install
