name       : irssi
version    : 0.8.20
release    : 9
source     :
    - https://github.com/irssi/irssi/releases/download/0.8.20/irssi-0.8.20.tar.gz : f5e20f76aa8237303c463e08adb3a3e3a400a24ba95acf73e9b068d634173f66
license    : GPL-2.0+
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %configure --sysconfdir=/etc/irssi \
               --with-socks \
               --with-bot \
               --with-proxy \
               --with-ncurses
build      : |
    %make
install    : |
    %make_install
