name       : irssi
version    : 1.2.1
release    : 24
source     :
    - git|https://github.com/irssi/irssi.git : 1.2.1
license    : GPL-2.0-or-later
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %autogen --sysconfdir=/etc/irssi \
        --with-bot \
        --with-ncurses \
        --with-proxy \
        --with-socks
build      : |
    %make
install    : |
    %make_install
