name       : irssi
version    : 1.0.0
release    : 10
source     :
    - https://github.com/irssi/irssi/releases/download/1.0.0/irssi-1.0.0.tar.xz : 6a8a3c1fc6a021a2c02a693877b2e19cbceb3eccd78fce49e44f596f4bae4fb8
license    : GPL-2.0+
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %configure --sysconfdir=/etc/irssi \
        --with-bot \
        --with-ncurses \
        --with-proxy \
        --with-socks
build      : |
    %make
install    : |
    %make_install
