name       : irssi
version    : 1.4.3
release    : 35
source     :
    - https://github.com/irssi/irssi/releases/download/1.4.3/irssi-1.4.3.tar.gz : 2cbaca493d4c36d3f1a6a2a0680ebdfe3bdabc202d9b8b99e49f4c83b7021591
homepage   : https://irssi.org/
license    : GPL-2.0-or-later
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %meson_configure --sysconfdir=/etc/irssi \
        -Dwith-bot=yes \
        -Dwith-proxy=yes \
        -Dwith-perl-lib=vendor
build      : |
    %ninja_build
install    : |
    %ninja_install

    # docs are available online
    rm -rf $installdir/usr/share/doc
