name       : irssi
version    : 1.2.1
release    : 25
source     :
    - https://github.com/irssi/irssi/releases/download/1.2.1/irssi-1.2.1.tar.xz : 5466a1ed9612cfa707d9a37d60b29d027b4ac7d83c74ceb1a410e2b59edba92c
license    : GPL-2.0-or-later
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %configure --sysconfdir=/etc/irssi \
        --with-bot \
        --with-ncurses \
        --with-proxy \
        --with-socks
build      : |
    %make
install    : |
    %make_install
