name        : irssi
version     : 0.8.17
release     : 4
source      :
    - http://www.irssi.org/files/irssi-0.8.17.tar.bz2 : 3c9600cad2edf58f1d012febc1a0ba844274df6e331c01a9e935467705166807
homepage    : http://www.irssi.org
license     :
    - GPLv2
summary     : Terminal based IRC client
description : |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more. The SolusOS build includes proxy and bot.
setup      : |
    %configure --sysconfdir=/etc/irssi \
               --with-socks \
               --with-bot \
               --with-proxy \
               --with-ncurses
build      : |
    %make
install    : |
    %make_install
