name       : irssi
version    : 1.0.1
release    : 11
source     :
    - https://github.com/irssi-import/irssi/releases/download/1.0.1/irssi-1.0.1.tar.xz : 9428c51a3f3598ffaef438c351a8d609cf10db34f2435bdcb84456226c383ccf
license    : GPL-2.0+
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %configure --sysconfdir=/etc/irssi \
        --with-bot \
        --with-ncurses \
        --with-proxy \
        --with-socks
build      : |
    %make
install    : |
    %make_install
