name       : irssi
version    : 1.4.4
release    : 38
source     :
    - https://github.com/irssi/irssi/releases/download/1.4.4/irssi-1.4.4.tar.gz : 90a4d459fb074deafbbea7b962a1423395122daaf8ad73f2b5927ae0ed808fd0
homepage   : https://irssi.org/
license    : GPL-2.0-or-later
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %meson_configure --sysconfdir=/etc/irssi \
        -Dwith-bot=yes \
        -Dwith-proxy=yes \
        -Dwith-perl-lib=vendor
build      : |
    %ninja_build
install    : |
    %ninja_install

    # docs are available online
    rm -rf $installdir/usr/share/doc
