name       : irssi
version    : 1.2.3
release    : 30
source     :
    - https://github.com/irssi/irssi/releases/download/1.2.3/irssi-1.2.3.tar.xz : a647bfefed14d2221fa77b6edac594934dc672c4a560417b1abcbbc6b88d769f
license    : GPL-2.0-or-later
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %configure --sysconfdir=/etc/irssi \
        --with-bot \
        --with-ncurses \
        --with-proxy \
        --with-socks \
        --with-perl-lib=vendor
build      : |
    %make
install    : |
    %make_install
    # Remove perllocal.pod
    rm -rf $installdir/%libdir%/perl5/5.32
