name       : irssi
version    : 1.2.2
release    : 29
source     :
    - https://github.com/irssi/irssi/releases/download/1.2.2/irssi-1.2.2.tar.xz : 6727060c918568ba2ff4295ad736128dba0b995d7b20491bca11f593bd857578
license    : GPL-2.0-or-later
summary    : Terminal based IRC client
component  : network.irc
description: |
    Irssi is a terminal based IRC client for UNIX systems with many features including autologging, theming abilities, proxy, scripting, keybindings, and more.
setup      : |
    %patch -p1 < $pkgfiles/glib-2-63.patch
    %configure --sysconfdir=/etc/irssi \
        --with-bot \
        --with-ncurses \
        --with-proxy \
        --with-socks \
        --with-perl-lib=vendor
build      : |
    %make
install    : |
    %make_install
    # Remove perllocal.pod
    rm -rf $installdir/%libdir%/perl5/5.32
